### PR TITLE
Added intro screen Feature

### PR DESCRIPTION
**Pull request by Moon613**

### CODE REVIEW

**Comment by SlimeCubed** [comment]
I think the feature type should be changed here. There are two options that I like better:
1 - Changing the feature to be a `PlayerString` would allow you to pick a custom image, independent of your slugcat's ID. This is consistent with the current scene system.
2 - Removing the feature entirely, instead adding each custom slugcat's title image if `$"illustrations/Intro_Roll_C_{name}.png"` exists. This is consistent with the current arena icon system.

I'm leaning towards the former, but I'd like to hear your thoughts!

**Comment by Moon613** [comment]
Yeah, option 1 does sound nicer just for QoL kind of stuff. I'm assuming that you're thinking of fully custom names, not bound to the need to have "intro_roll_c_"  in the image file name?

**Comment by Moon613** [comment]
Ok, I got around to updating the way it adds the title screen image, and it just uses a PlayerString like you suggested. As long as an image file exists in the mod's illustrations folder exactly matching the name provided to the feature, it will use that image.

**Comment by SlimeCubed** [comment]
I made some changes to the IL hook that should make it more compatible. Namely, the new version doesn't remove instructions and doesn't use a hardcoded list of MSC slugcat names. It was *probably* fine before, but with how many people have SlugBase installed I try to play it as safe as possible.

Thanks for contributing!

**Pull request merged**
